language: android
android:
  components:
    - tools
    - build-tools-21.1.2
    - android-21
    - extra
after_failure: "cat /home/travis/build/ftcgearedup/ftc_app/TeamCode/build/outputs/lint-results-debug.xml"
